export type AvailableJobRU = keyof typeof JOB2RUSSIAN;

/** Icon map of jobs to their fontawesome5 (free) counterpart. */
export const JOB2RUSSIAN = {
  'AI': 'ИИ',
  'Assistant': 'Ассистент',
  'Atmospheric Technician': 'Атмосферный Техник',
  'Bartender': 'Бармен',
  'Bitrunner': 'Битраннер',
  'Botanist': 'Ботаник',
  'Captain': 'Капитан',
  'Cargo Technician': 'Грузчик',
  'Chaplain': 'Капеллан',
  'Chemist': 'Химик',
  'Chief Engineer': 'Старший Инженер',
  'Chief Medical Officer': 'Главный Врач',
  'Clown': 'Клоун',
  'Cook': 'Повар',
  'Coroner': 'Коронер',
  'Curator': 'Куратор',
  'Cyborg': 'Киборг',
  'Detective': 'Детектив',
  'Geneticist': 'Генетик',
  'Head of Personnel': 'Глава Персонала',
  'Head of Security': 'Начальник Охраны',
  'Janitor': 'Уборщик',
  'Lawyer': 'Адвокат',
  'Medical Doctor': 'Врач',
  'Mime': 'Мим',
  'Paramedic': 'Парамедик',
  'Prisoner': 'Заключённый',
  'Psychologist': 'Психолог',
  'Quartermaster': 'Квартирмейстер',
  'Research Director': 'Научный Руководитель',
  'Roboticist': 'Робототехник',
  'Scientist': 'Учёный',
  'Security Officer (Cargo)': 'Офицер (Снабжение)',
  'Security Officer (Engineering)': 'Офицер (Инженерный)',
  'Security Officer (Medical)': 'Офицер (Медбей)',
  'Security Officer (Science)': 'Офицер (Научный)',
  'Security Officer': 'Офицер',
  'Shaft Miner': 'Шахтёр',
  'Station Engineer': 'Инженер',
  'Virologist': 'Вирусолог',
  'Warden': 'Надзиратель',
} as const;
